// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDf_rcU8G2UuRyfAjwmLQ4Edkb7GRQX-ro',
    appId: '1:97075895825:web:f024753b325bc6eb911bb0',
    messagingSenderId: '97075895825',
    projectId: 'reyogo-9f5ad',
    authDomain: 'reyogo-9f5ad.firebaseapp.com',
    storageBucket: 'reyogo-9f5ad.firebasestorage.app',
    measurementId: 'G-GGZMGND418',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcu0lAB9iDEuHWg5qNDenjCZAZMrTM2h4',
    appId: '1:97075895825:android:25bcbfa1627a5216911bb0',
    messagingSenderId: '97075895825',
    projectId: 'reyogo-9f5ad',
    storageBucket: 'reyogo-9f5ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqWBzqp0JiDK78tWXbZD7iJyvbvqctd6U',
    appId: '1:97075895825:ios:678dd2d4d1b0f08b911bb0',
    messagingSenderId: '97075895825',
    projectId: 'reyogo-9f5ad',
    storageBucket: 'reyogo-9f5ad.firebasestorage.app',
    iosBundleId: 'com.example.goldPrice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqWBzqp0JiDK78tWXbZD7iJyvbvqctd6U',
    appId: '1:97075895825:ios:678dd2d4d1b0f08b911bb0',
    messagingSenderId: '97075895825',
    projectId: 'reyogo-9f5ad',
    storageBucket: 'reyogo-9f5ad.firebasestorage.app',
    iosBundleId: 'com.example.goldPrice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDf_rcU8G2UuRyfAjwmLQ4Edkb7GRQX-ro',
    appId: '1:97075895825:web:f9578fa46decc350911bb0',
    messagingSenderId: '97075895825',
    projectId: 'reyogo-9f5ad',
    authDomain: 'reyogo-9f5ad.firebaseapp.com',
    storageBucket: 'reyogo-9f5ad.firebasestorage.app',
    measurementId: 'G-14G75DV05N',
  );
}
