import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // generated by flutterfire CLI
import 'core/theme.dart';
import 'view_models/gold_view_model.dart';
import 'views/splash/splash_screen.dart';
import 'views/login/login_page.dart';
import 'views/login/signup_page.dart';
import 'views/login/forgot_password_page.dart';
import 'views/login/otp_verification_page.dart';
import 'views/home/home_page.dart';
import 'core/navigation_service.dart'; // 👈 add this import

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  print('Firebase projectId: ${Firebase.app().options.projectId}');
  runApp(
    MultiProvider(
      providers: [ChangeNotifierProvider(create: (_) => GoldViewModel())],
      child: const ReyogoApp(),
    ),
  );
}

class ReyogoApp extends StatelessWidget {
  const ReyogoApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      navigatorKey: navigatorKey, // 👈 add this

      debugShowCheckedModeBanner: false,
      title: 'Reyogo Gold',
      theme: AppTheme.lightTheme,
      initialRoute: '/login',
      routes: {
        '/login': (_) => const LoginPage(),
        '/signup': (_) => const SignupPage(),
        '/forgot': (_) => const ForgotPasswordPage(),
        '/otp': (_) => const OtpVerificationPage(),
        '/splash': (_) => const SplashScreen(),
        '/home': (_) => const HomePage(),
      },
    );
  }
}
